  - name: install apache/httpd
    yum: 
      name: "{{ service_name }}"
      state: latest

  - name: start and enable apache/httpd service
    service: 
      name: "{{ service_name }}"
      state: started
      enabled: yes

  - name: create default index.html
    copy:
      content: "Hello World {{ app_num }}"
      dest: /var/www/html/index.html
